dist: xenial
language: go
go:
    - "1.12.2"

# before_install
# install - install any dependencies required
install:
    - go get -u github.com/gohugoio/hugo    # consume time 70.85s

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - bash scripts/publish_to_ghpages.sh
